import { ListMenuType } from "../types/typeGlobal";

import {
    nam1Menulist,
    nam2Menulist,
    nu1Menulist,
    nu2Menulist,
    benam1Menulist,
    benam2Menulist,
    benu1Menulist,
    benu2Menulist,
} from "../../assets";

export const initialListMenu: ListMenuType[] = [
    {
        name: "Nữ",
        url: "/women",
        hangmoi: ["Hàng mới về", "Áo phong cách", "disney"],
        noibat: ["Giá tốt"],
        dmsp: [
            "Áo phông/ Áo thun",
            "Áo polo ",
            "Áo sơ mi & Áo kiểu ",
            "Áo chống nắng",
            "Canifa Active/ Quần áo thể thao",
            "Quần soóc/ Quần short",
            "Quần dài & Quần Jean",
            "Quần áo nỉ",
            "Quần áo nỉ",
            "Quần áo mặc nhà/ Đồ ngủ",
            "Áo khoác & Giữ nhiệt",
            "Áo len",
            "Bộ quần áo",
            "Đồ lót",
            "Tất/Vớ",
        ],
        phukien: ["Hàng mới về", "Áo phong cách", "disney"],
        image1: nu1Menulist,
        image2: nu2Menulist,
    },
    {
        name: "Nam",
        url: "/men",
        hangmoi: ["Hàng mới về", "Áo phong cách", "disney"],
        noibat: ["Giá tốt"],
        dmsp: [
            "Áo phông/ Áo thun",
            "Áo polo ",
            "Áo sơ mi & Áo kiểu ",
            "Áo chống nắng",
            "Canifa Active/ Quần áo thể thao",
            "Quần soóc/ Quần short",
            "Quần dài & Quần Jean",
            "Quần áo nỉ",
            "Quần áo nỉ",
            "Quần áo mặc nhà/ Đồ ngủ",
            "Áo khoác & Giữ nhiệt",
            "Áo len",
            "Bộ quần áo",
            "Đồ lót",
            "Tất/Vớ",
        ],
        phukien: ["Hàng mới về", "Áo phong cách", "disney"],
        image1: nam1Menulist,
        image2: nam2Menulist,
    },
    {
        name: "Bé Gái",
        url: "/girl",
        hangmoi: ["Hàng mới về", "Áo phong cách", "disney"],
        noibat: ["Giá tốt"],
        dmsp: [
            "Áo phông/ Áo thun",
            "Áo polo ",
            "Áo sơ mi & Áo kiểu ",
            "Áo chống nắng",
            "Canifa Active/ Quần áo thể thao",
            "Quần soóc/ Quần short",
            "Quần dài & Quần Jean",
            "Quần áo nỉ",
            "Quần áo nỉ",
            "Quần áo mặc nhà/ Đồ ngủ",
            "Áo khoác & Giữ nhiệt",
            "Áo len",
            "Bộ quần áo",
            "Đồ lót",
            "Tất/Vớ",
        ],
        phukien: ["Hàng mới về", "Áo phong cách", "disney"],
        image1: benu1Menulist,
        image2: benu2Menulist,
    },
    {
        name: "Bé Trai",
        url: "/boy",
        hangmoi: ["Hàng mới về", "Áo phong cách", "disney"],
        noibat: ["Giá tốt"],
        dmsp: [
            "Áo phông/ Áo thun",
            "Áo polo ",
            "Áo sơ mi & Áo kiểu ",
            "Áo chống nắng",
            "Canifa Active/ Quần áo thể thao",
            "Quần soóc/ Quần short",
            "Quần dài & Quần Jean",
            "Quần áo nỉ",
            "Quần áo nỉ",
            "Quần áo mặc nhà/ Đồ ngủ",
            "Áo khoác & Giữ nhiệt",
            "Áo len",
            "Bộ quần áo",
            "Đồ lót",
            "Tất/Vớ",
        ],
        phukien: ["Hàng mới về", "Áo phong cách", "disney"],
        image1: benam1Menulist,
        image2: benam2Menulist,
    },
];